import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/Sidebars/AppSideBar";
import { ThemeProvider } from "@/context/ThemeContext";
import { LanguageProvider } from "@/context/LanguageContext";
import ThemeToggle from "@/components/ThemeToggle";
import AppPopupProvider from "@/components/AppPopupProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Retainly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <LanguageProvider>               {/* ← add this */}
            <SidebarProvider>
              <AppPopupProvider />
              <AppSideBar />
              <main className="flex-1 w-full">
                <SidebarTrigger className="bg-accent m-2 p-5 fixed z-50" />
                {children}
              </main>
            </SidebarProvider>
            <ThemeToggle />
          </LanguageProvider>             {/* ← and close here */}
        </ThemeProvider>
      </body>
    </html>
  );
}