import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai } from "next/font/google";
import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSideBar from "@/components/Sidebars/AppSideBar";
import { ThemeProvider } from "@/context/ThemeContext";
import { LanguageProvider } from "@/context/LanguageContext";
import ThemeToggle from "@/components/ThemeToggle";
import AppPopupProvider from "@/components/AppPopupProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai"]
})

export const metadata: Metadata = {
  title: "Retainly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSansThai.variable} font-sans antialiased`}>
        <ThemeProvider>
          <LanguageProvider>
            <SidebarProvider>
              <AppPopupProvider />
              <AppSideBar />
              <main className="flex-1 w-full">
                <SidebarTrigger className="fixed left-2 top-4 z-40 h-7 w-7 rounded-lg border shadow-sm bg-background hover:bg-muted transition-colors" />
                {children}
              </main>
            </SidebarProvider>
            <ThemeToggle />
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}